// app/src/App.tsx
import React, {useEffect, useState} from 'react';
import styled from "styled-components";

// const apiBaseUrl = "https://localhost:7072/api";
const apiBaseUrl = "https://metrix-api.azurewebsites.net/api";

interface IMeasurement {
  dateTime: string,
  value: number
}

export const App: React.FC = () => {
  const [measurements, setMeasurements] = useState<IMeasurement[]>([]);
  const [errorMessage, setErrorMessage] = useState<string>();

  useEffect(() => {
    fetch(new Request(apiBaseUrl + "/Measurements?metricKey=foo_bar"))
      .then(response => response.json().then(data => setMeasurements(data)))
      .catch(err => setErrorMessage(JSON.stringify(err)));
  }, []);

  return <>
    <Title>Metrix</Title>
    {measurements.length > 0
      ? (<ul>{measurements.map(m => <li key={m.dateTime}>{m.dateTime}: {m.value}</li>)}</ul>)
      : null}
    {errorMessage ? (<Error>{errorMessage}</Error>) : null}
  </>;
};


const Title = styled.h1`
  color: darkgreen;
`;

const Error = styled.div`
  color: darkred;
`

// app/src/App.svelte
<script lang="ts">
	let resultMessage = "";
	let errorMessage = "";

	fetch(new Request("https://metrix-api.azurewebsites.net/salimax"))
			.then(response => response.json())
			.then(result =>  resultMessage = "Success: " + JSON.stringify(result))
			.catch(error => errorMessage = "Error: " + JSON.stringify(error));
</script>

<main>
	<h1>Sali Max</h1>
	<div class="success">{resultMessage}</div>
	<div class="error">{errorMessage}</div>
</main>

<style>
	.success {
		color: darkgreen;
	}

	.error {
		color: darkred;
	}
</style>
